version: '3'
services:
  db:
    image: postgres:10.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      MIX_ENV: dev
      PORT: 4000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    command: ./run.sh
    ports:
      - "4000:4000"
    depends_on:
      - db
        #
### Named Volumes ###
volumes:
  db_data:
    driver: local
